title: Template Jekyll Datasite
email: dansonguyen@gmail.com
description: |
  A template for projects that require data ETL, static Github pages hosting, and some D3 fun


baseurl: "/jekyll-datasite-template" # the subpath of your site, e.g. /blog
url: "https://dannguyen.github.io" # the base hostname & protocol for your site,

twitter_username: dancow
github_username:  dannguyen
repository: dannguyen/jekyll-datasite-template

github:
  build_revision: 0.0.1
  username: dannguyen
  repository: dannguyen/jekyll-datasite-template
  repository_url: https://github.com/dannguyen/jekyll-datasite-template
# Build settings
plugins:
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# page_gen-dirs: true
# page_gen:
#   - index_files: true
#     data: 'state_summaries.states'
#     name: 'abbr'
#     template: 'state_page'
#     dir: 'states'
